AI_set:
  type: 1
#  AI类型，0为不配置ai,1为讯飞星火AI，2为deepseekAI
PATH:
  path: D:\学习通考试客户端\考试客户端
SPARK:
  Spark_url: wss://spark-api.xf-yun.com/v1.1/chat
  api_key: 5b2302f3ac2295e56bd13f587d7ffa6e
  api_secret: YWY0MWJhNTM4MGU3NTJkZDJiMDM0ZjZl
  appid: 1b69309b
  domain: lite
#  ;讯飞星火ai配置说明
#  ;appid=
#  ;api_secret=
#  ;api_key=
#  ;appid、api_secret、api_key三个服务认证信息请前往开放平台控制台查看（https://console.xfyun.cn/services/bm35）
#
#  ;Spark_url= wss://spark-api.xf-yun.com/v3.5/chat   Max环境的地址
#  ;Spark_url = wss://spark-api.xf-yun.com/v4.0/chat   4.0Ultra环境的地址
#  ;Spark_url = wss://spark-api.xf-yun.com/v3.1/chat   Pro环境的地址
#  ;Spark_url = wss://spark-api.xf-yun.com/v1.1/chat   Lite环境的地址
#
#  ;domain=generalv3.5    Max版本
#  ;domain = 4.0Ultra     4.0Ultra 版本
#  ;domain = generalv3    Pro版本
#  ;domain = lite         Lite版本址
deepseek:
  api_key:
  model: deepseek-chat
#  ;model = deepseek-reasoner
#  ;api充值地址(https://www.deepseek.com)
#  ;如果是第三方接入deepseek，请修改函数call_deepseek_api中的url
#  ;自用的申请地址(https://www.api4gpt.com/register?aff=uZgA)，接口url(https://one.api4gpt.com/v1/chat/completions)
